<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2Y7TCc\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2Y7TCc/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2Y7TCc.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJ2Y7TCc\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJ2Y7TCc\App_KernelTestDebugContainer([
    'container.build_hash' => 'J2Y7TCc',
    'container.build_id' => 'ec92819a',
    'container.build_time' => 1586739158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2Y7TCc');
