<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCBUh80N\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCBUh80N/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCBUh80N.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCBUh80N\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCBUh80N\App_KernelTestDebugContainer([
    'container.build_hash' => 'CBUh80N',
    'container.build_id' => '8ee5e400',
    'container.build_time' => 1586547423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCBUh80N');
