<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerULSlq23\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerULSlq23/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerULSlq23.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerULSlq23\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerULSlq23\App_KernelTestDebugContainer([
    'container.build_hash' => 'ULSlq23',
    'container.build_id' => '58492848',
    'container.build_time' => 1586186525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerULSlq23');
