<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD2nSdfU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD2nSdfU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD2nSdfU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD2nSdfU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD2nSdfU\App_KernelDevDebugContainer([
    'container.build_hash' => 'D2nSdfU',
    'container.build_id' => '0f3aacb5',
    'container.build_time' => 1585830158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD2nSdfU');
