<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMeDdp8x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMeDdp8x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMeDdp8x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMeDdp8x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMeDdp8x\App_KernelDevDebugContainer([
    'container.build_hash' => 'MeDdp8x',
    'container.build_id' => '6188a951',
    'container.build_time' => 1583319673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMeDdp8x');
