<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVcCQVw9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVcCQVw9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVcCQVw9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVcCQVw9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVcCQVw9\App_KernelDevDebugContainer([
    'container.build_hash' => 'VcCQVw9',
    'container.build_id' => '38db4e1f',
    'container.build_time' => 1585593313,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVcCQVw9');
