<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'listing_show' => [['listingId'], ['listingId' => null, '_controller' => 'App\\Controller\\ListingController::show'], ['listingId' => '\\d+'], [['variable', '/', '\\d+', 'listingId', true]], [], []],
    'listing_create' => [[], ['_controller' => 'App\\Controller\\ListingController::create'], [], [['text', '/new']], [], []],
    'listing_delete' => [['listingId'], ['_controller' => 'App\\Controller\\ListingController::delete'], ['listingId' => '\\d+'], [['text', '/delete'], ['variable', '/', '\\d+', 'listingId', true]], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/inscription']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
    'task_create' => [['listingId'], ['_controller' => 'App\\Controller\\TaskController::create'], ['listingId' => '\\d+'], [['text', '/task/new'], ['variable', '/', '\\d+', 'listingId', true]], [], []],
    'task_edit' => [['listingId', 'taskId'], ['_controller' => 'App\\Controller\\TaskController::edit'], ['listingId' => '\\d+', 'taskId' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'taskId', true], ['text', '/task'], ['variable', '/', '\\d+', 'listingId', true]], [], []],
    'task_delete' => [['listingId', 'taskId'], ['_controller' => 'App\\Controller\\TaskController::delete'], ['listingId' => '\\d+', 'taskId' => '\\d+'], [['text', '/delete'], ['variable', '/', '\\d+', 'taskId', true], ['text', '/task'], ['variable', '/', '\\d+', 'listingId', true]], [], []],
];
